/**
 *
 * $Id$
 */
package hub.sam.dbl.validation;

import hub.sam.dbl.Constructor;
import hub.sam.dbl.Function;
import hub.sam.dbl.LocalScope;
import hub.sam.dbl.NativeBinding;
import hub.sam.dbl.SuperClassSpecification;
import hub.sam.dbl.Variable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.dbl.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateActive(boolean value);
	boolean validateBindings(EList<NativeBinding> value);
	boolean validateSuperClasses(EList<SuperClassSpecification> value);
	boolean validateConstructors(EList<Constructor> value);
	boolean validateAttributes(EList<Variable> value);
	boolean validateMethods(EList<Function> value);
	boolean validateActionsBlock(LocalScope value);
}
