/**
 *
 * $Id$
 */
package hub.sam.dbl.validation;

import hub.sam.dbl.ExpansionPart;
import hub.sam.dbl.Expression;

import hub.sam.dbl.IdExpr;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.dbl.ExpansionStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpansionStatementValidator {
	boolean validate();

	boolean validateClassContext(boolean value);

	boolean validateFunctionContext(boolean value);

	boolean validateVariableContext(boolean value);

	boolean validateDifferingContext(IdExpr value);

	boolean validateParts(EList<ExpansionPart> value);
	boolean validateExprs(EList<Expression> value);
}
