/**
 *
 * $Id$
 */
package hub.sam.dbl.validation;

import hub.sam.dbl.ExtensibleElement;


/**
 * A sample validator interface for {@link hub.sam.dbl.ExtensibleElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExtensibleElementValidator {
	boolean validate();

	boolean validateConcreteSyntax(String value);
	boolean validateInstanceOfExtensionDefinition(boolean value);

	boolean validatePlaceHolder1(ExtensibleElement value);

	boolean validatePlaceHolder2(ExtensibleElement value);

	boolean validatePlaceHolder3(ExtensibleElement value);

	boolean validatePlaceHolder4(ExtensibleElement value);

	boolean validatePlaceHolder5(ExtensibleElement value);

	boolean validatePlaceHolder6(ExtensibleElement value);

	boolean validatePlaceHolder8(ExtensibleElement value);

	boolean validatePlaceHolder9(ExtensibleElement value);

	boolean validatePlaceHolder10(ExtensibleElement value);
}
