/**
 *
 * $Id$
 */
package hub.sam.dbl.validation;

import hub.sam.dbl.LanguageConceptClassifier;
import hub.sam.dbl.TextualSyntaxDef;

/**
 * A sample validator interface for {@link hub.sam.dbl.ExtensionDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExtensionDefinitionValidator {
	boolean validate();

	boolean validateExtendedConcept(LanguageConceptClassifier value);
	boolean validateAbstractSyntaxDef(hub.sam.dbl.Class value);
	boolean validateTextualSyntaxDef(TextualSyntaxDef value);
}
