/**
 *
 * $Id$
 */
package hub.sam.dbl.validation;

import hub.sam.dbl.ExtensionDefinition;
import hub.sam.dbl.ExtensionSemanticsDefinition;
import hub.sam.dbl.Function;
import hub.sam.dbl.Variable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.dbl.Module}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleValidator {
	boolean validate();

	boolean validateClasses(EList<hub.sam.dbl.Class> value);
	boolean validateExtensionDefinitions(EList<ExtensionDefinition> value);
	boolean validateExtensionSemanticsDefinitions(EList<ExtensionSemanticsDefinition> value);
	boolean validateFunctions(EList<Function> value);
	boolean validateVariables(EList<Variable> value);
}
