/**
 *
 * $Id$
 */
package hub.sam.dbl.validation;

import hub.sam.dbl.ArrayDimension;
import hub.sam.dbl.IdExpr;
import hub.sam.dbl.PrimitiveType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.dbl.TypedElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypedElementValidator {
	boolean validate();

	boolean validatePrimitiveType(PrimitiveType value);
	boolean validateTypeArrayDimensions(EList<ArrayDimension> value);
	boolean validateClassifierType(IdExpr value);
}
