/**
 */
package hub.sam.dbl.provider;

import hub.sam.dbl.util.DblAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DblItemProviderAdapterFactory extends DblAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DblItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Construct} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstructItemProvider constructItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Construct}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstructAdapter() {
		if (constructItemProvider == null) {
			constructItemProvider = new ConstructItemProvider(this);
		}

		return constructItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ExtensibleElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtensibleElementItemProvider extensibleElementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ExtensibleElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtensibleElementAdapter() {
		if (extensibleElementItemProvider == null) {
			extensibleElementItemProvider = new ExtensibleElementItemProvider(this);
		}

		return extensibleElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Model} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelItemProvider modelItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Model}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelAdapter() {
		if (modelItemProvider == null) {
			modelItemProvider = new ModelItemProvider(this);
		}

		return modelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Import} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportItemProvider importItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportAdapter() {
		if (importItemProvider == null) {
			importItemProvider = new ImportItemProvider(this);
		}

		return importItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Module} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModuleItemProvider moduleItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Module}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModuleAdapter() {
		if (moduleItemProvider == null) {
			moduleItemProvider = new ModuleItemProvider(this);
		}

		return moduleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ConstructiveExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstructiveExtensionItemProvider constructiveExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ConstructiveExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstructiveExtensionAdapter() {
		if (constructiveExtensionItemProvider == null) {
			constructiveExtensionItemProvider = new ConstructiveExtensionItemProvider(this);
		}

		return constructiveExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ModuleContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModuleContentItemProvider moduleContentItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ModuleContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModuleContentAdapter() {
		if (moduleContentItemProvider == null) {
			moduleContentItemProvider = new ModuleContentItemProvider(this);
		}

		return moduleContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ClassContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassContentItemProvider classContentItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ClassContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassContentAdapter() {
		if (classContentItemProvider == null) {
			classContentItemProvider = new ClassContentItemProvider(this);
		}

		return classContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ArrayDimension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayDimensionItemProvider arrayDimensionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ArrayDimension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayDimensionAdapter() {
		if (arrayDimensionItemProvider == null) {
			arrayDimensionItemProvider = new ArrayDimensionItemProvider(this);
		}

		return arrayDimensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.VoidType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VoidTypeItemProvider voidTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.VoidType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVoidTypeAdapter() {
		if (voidTypeItemProvider == null) {
			voidTypeItemProvider = new VoidTypeItemProvider(this);
		}

		return voidTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.IntType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntTypeItemProvider intTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.IntType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntTypeAdapter() {
		if (intTypeItemProvider == null) {
			intTypeItemProvider = new IntTypeItemProvider(this);
		}

		return intTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.BoolType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BoolTypeItemProvider boolTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.BoolType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBoolTypeAdapter() {
		if (boolTypeItemProvider == null) {
			boolTypeItemProvider = new BoolTypeItemProvider(this);
		}

		return boolTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.DoubleType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DoubleTypeItemProvider doubleTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.DoubleType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDoubleTypeAdapter() {
		if (doubleTypeItemProvider == null) {
			doubleTypeItemProvider = new DoubleTypeItemProvider(this);
		}

		return doubleTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.StringType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringTypeItemProvider stringTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.StringType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringTypeAdapter() {
		if (stringTypeItemProvider == null) {
			stringTypeItemProvider = new StringTypeItemProvider(this);
		}

		return stringTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Function} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionItemProvider functionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Function}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAdapter() {
		if (functionItemProvider == null) {
			functionItemProvider = new FunctionItemProvider(this);
		}

		return functionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.NativeBinding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NativeBindingItemProvider nativeBindingItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.NativeBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNativeBindingAdapter() {
		if (nativeBindingItemProvider == null) {
			nativeBindingItemProvider = new NativeBindingItemProvider(this);
		}

		return nativeBindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.SuperClassSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SuperClassSpecificationItemProvider superClassSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.SuperClassSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSuperClassSpecificationAdapter() {
		if (superClassSpecificationItemProvider == null) {
			superClassSpecificationItemProvider = new SuperClassSpecificationItemProvider(this);
		}

		return superClassSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Class} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassItemProvider classItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Class}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassAdapter() {
		if (classItemProvider == null) {
			classItemProvider = new ClassItemProvider(this);
		}

		return classItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Constructor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstructorItemProvider constructorItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Constructor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstructorAdapter() {
		if (constructorItemProvider == null) {
			constructorItemProvider = new ConstructorItemProvider(this);
		}

		return constructorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Variable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableItemProvider variableItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Variable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableAdapter() {
		if (variableItemProvider == null) {
			variableItemProvider = new VariableItemProvider(this);
		}

		return variableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.NamedElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamedElementItemProvider namedElementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.NamedElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamedElementAdapter() {
		if (namedElementItemProvider == null) {
			namedElementItemProvider = new NamedElementItemProvider(this);
		}

		return namedElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Statement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StatementItemProvider statementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Statement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStatementAdapter() {
		if (statementItemProvider == null) {
			statementItemProvider = new StatementItemProvider(this);
		}

		return statementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.LoopStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoopStatementItemProvider loopStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.LoopStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoopStatementAdapter() {
		if (loopStatementItemProvider == null) {
			loopStatementItemProvider = new LoopStatementItemProvider(this);
		}

		return loopStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.SimpleStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SimpleStatementItemProvider simpleStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.SimpleStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSimpleStatementAdapter() {
		if (simpleStatementItemProvider == null) {
			simpleStatementItemProvider = new SimpleStatementItemProvider(this);
		}

		return simpleStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Assignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssignmentItemProvider assignmentItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Assignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssignmentAdapter() {
		if (assignmentItemProvider == null) {
			assignmentItemProvider = new AssignmentItemProvider(this);
		}

		return assignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.FunctionCall} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionCallItemProvider functionCallItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.FunctionCall}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionCallAdapter() {
		if (functionCallItemProvider == null) {
			functionCallItemProvider = new FunctionCallItemProvider(this);
		}

		return functionCallItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Return} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnItemProvider returnItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Return}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnAdapter() {
		if (returnItemProvider == null) {
			returnItemProvider = new ReturnItemProvider(this);
		}

		return returnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.WaitUntil} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WaitUntilItemProvider waitUntilItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.WaitUntil}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWaitUntilAdapter() {
		if (waitUntilItemProvider == null) {
			waitUntilItemProvider = new WaitUntilItemProvider(this);
		}

		return waitUntilItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Terminate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TerminateItemProvider terminateItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Terminate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTerminateAdapter() {
		if (terminateItemProvider == null) {
			terminateItemProvider = new TerminateItemProvider(this);
		}

		return terminateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Yield} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YieldItemProvider yieldItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Yield}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYieldAdapter() {
		if (yieldItemProvider == null) {
			yieldItemProvider = new YieldItemProvider(this);
		}

		return yieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Wait} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WaitItemProvider waitItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Wait}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWaitAdapter() {
		if (waitItemProvider == null) {
			waitItemProvider = new WaitItemProvider(this);
		}

		return waitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Reactivate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReactivateItemProvider reactivateItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Reactivate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReactivateAdapter() {
		if (reactivateItemProvider == null) {
			reactivateItemProvider = new ReactivateItemProvider(this);
		}

		return reactivateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ActivateObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivateObjectItemProvider activateObjectItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ActivateObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActivateObjectAdapter() {
		if (activateObjectItemProvider == null) {
			activateObjectItemProvider = new ActivateObjectItemProvider(this);
		}

		return activateObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Advance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AdvanceItemProvider advanceItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Advance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAdvanceAdapter() {
		if (advanceItemProvider == null) {
			advanceItemProvider = new AdvanceItemProvider(this);
		}

		return advanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Print} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrintItemProvider printItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Print}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrintAdapter() {
		if (printItemProvider == null) {
			printItemProvider = new PrintItemProvider(this);
		}

		return printItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.IfStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IfStatementItemProvider ifStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.IfStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIfStatementAdapter() {
		if (ifStatementItemProvider == null) {
			ifStatementItemProvider = new IfStatementItemProvider(this);
		}

		return ifStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.LocalScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalScopeItemProvider localScopeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.LocalScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalScopeAdapter() {
		if (localScopeItemProvider == null) {
			localScopeItemProvider = new LocalScopeItemProvider(this);
		}

		return localScopeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.LocalScopeStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalScopeStatementItemProvider localScopeStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.LocalScopeStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalScopeStatementAdapter() {
		if (localScopeStatementItemProvider == null) {
			localScopeStatementItemProvider = new LocalScopeStatementItemProvider(this);
		}

		return localScopeStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ForStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForStatementItemProvider forStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ForStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForStatementAdapter() {
		if (forStatementItemProvider == null) {
			forStatementItemProvider = new ForStatementItemProvider(this);
		}

		return forStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.WhileStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WhileStatementItemProvider whileStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.WhileStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhileStatementAdapter() {
		if (whileStatementItemProvider == null) {
			whileStatementItemProvider = new WhileStatementItemProvider(this);
		}

		return whileStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.SwitchStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwitchStatementItemProvider switchStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.SwitchStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwitchStatementAdapter() {
		if (switchStatementItemProvider == null) {
			switchStatementItemProvider = new SwitchStatementItemProvider(this);
		}

		return switchStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.SwitchCase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwitchCaseItemProvider switchCaseItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.SwitchCase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwitchCaseAdapter() {
		if (switchCaseItemProvider == null) {
			switchCaseItemProvider = new SwitchCaseItemProvider(this);
		}

		return switchCaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.BreakStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BreakStatementItemProvider breakStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.BreakStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBreakStatementAdapter() {
		if (breakStatementItemProvider == null) {
			breakStatementItemProvider = new BreakStatementItemProvider(this);
		}

		return breakStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ContinueStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContinueStatementItemProvider continueStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ContinueStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContinueStatementAdapter() {
		if (continueStatementItemProvider == null) {
			continueStatementItemProvider = new ContinueStatementItemProvider(this);
		}

		return continueStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Expression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpressionItemProvider expressionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Expression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpressionAdapter() {
		if (expressionItemProvider == null) {
			expressionItemProvider = new ExpressionItemProvider(this);
		}

		return expressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L1Expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L1ExprItemProvider l1ExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L1Expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL1ExprAdapter() {
		if (l1ExprItemProvider == null) {
			l1ExprItemProvider = new L1ExprItemProvider(this);
		}

		return l1ExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L2Expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L2ExprItemProvider l2ExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L2Expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL2ExprAdapter() {
		if (l2ExprItemProvider == null) {
			l2ExprItemProvider = new L2ExprItemProvider(this);
		}

		return l2ExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L3Expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L3ExprItemProvider l3ExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L3Expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL3ExprAdapter() {
		if (l3ExprItemProvider == null) {
			l3ExprItemProvider = new L3ExprItemProvider(this);
		}

		return l3ExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L4Expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L4ExprItemProvider l4ExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L4Expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL4ExprAdapter() {
		if (l4ExprItemProvider == null) {
			l4ExprItemProvider = new L4ExprItemProvider(this);
		}

		return l4ExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L5Expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L5ExprItemProvider l5ExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L5Expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL5ExprAdapter() {
		if (l5ExprItemProvider == null) {
			l5ExprItemProvider = new L5ExprItemProvider(this);
		}

		return l5ExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L6Expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L6ExprItemProvider l6ExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L6Expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL6ExprAdapter() {
		if (l6ExprItemProvider == null) {
			l6ExprItemProvider = new L6ExprItemProvider(this);
		}

		return l6ExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L7Expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L7ExprItemProvider l7ExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L7Expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL7ExprAdapter() {
		if (l7ExprItemProvider == null) {
			l7ExprItemProvider = new L7ExprItemProvider(this);
		}

		return l7ExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L8Expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L8ExprItemProvider l8ExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L8Expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL8ExprAdapter() {
		if (l8ExprItemProvider == null) {
			l8ExprItemProvider = new L8ExprItemProvider(this);
		}

		return l8ExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L9Expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L9ExprItemProvider l9ExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L9Expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL9ExprAdapter() {
		if (l9ExprItemProvider == null) {
			l9ExprItemProvider = new L9ExprItemProvider(this);
		}

		return l9ExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Or} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrItemProvider orItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Or}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrAdapter() {
		if (orItemProvider == null) {
			orItemProvider = new OrItemProvider(this);
		}

		return orItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.And} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AndItemProvider andItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.And}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAndAdapter() {
		if (andItemProvider == null) {
			andItemProvider = new AndItemProvider(this);
		}

		return andItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.NotEqual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotEqualItemProvider notEqualItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.NotEqual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNotEqualAdapter() {
		if (notEqualItemProvider == null) {
			notEqualItemProvider = new NotEqualItemProvider(this);
		}

		return notEqualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Equal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EqualItemProvider equalItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Equal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqualAdapter() {
		if (equalItemProvider == null) {
			equalItemProvider = new EqualItemProvider(this);
		}

		return equalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Greater} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GreaterItemProvider greaterItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Greater}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGreaterAdapter() {
		if (greaterItemProvider == null) {
			greaterItemProvider = new GreaterItemProvider(this);
		}

		return greaterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.GreaterEqual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GreaterEqualItemProvider greaterEqualItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.GreaterEqual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGreaterEqualAdapter() {
		if (greaterEqualItemProvider == null) {
			greaterEqualItemProvider = new GreaterEqualItemProvider(this);
		}

		return greaterEqualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Less} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LessItemProvider lessItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Less}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLessAdapter() {
		if (lessItemProvider == null) {
			lessItemProvider = new LessItemProvider(this);
		}

		return lessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.LessEqual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LessEqualItemProvider lessEqualItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.LessEqual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLessEqualAdapter() {
		if (lessEqualItemProvider == null) {
			lessEqualItemProvider = new LessEqualItemProvider(this);
		}

		return lessEqualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.InstanceOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InstanceOfItemProvider instanceOfItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.InstanceOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInstanceOfAdapter() {
		if (instanceOfItemProvider == null) {
			instanceOfItemProvider = new InstanceOfItemProvider(this);
		}

		return instanceOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Plus} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlusItemProvider plusItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Plus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlusAdapter() {
		if (plusItemProvider == null) {
			plusItemProvider = new PlusItemProvider(this);
		}

		return plusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Minus} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MinusItemProvider minusItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Minus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMinusAdapter() {
		if (minusItemProvider == null) {
			minusItemProvider = new MinusItemProvider(this);
		}

		return minusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Mul} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MulItemProvider mulItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Mul}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMulAdapter() {
		if (mulItemProvider == null) {
			mulItemProvider = new MulItemProvider(this);
		}

		return mulItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Mod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModItemProvider modItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Mod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModAdapter() {
		if (modItemProvider == null) {
			modItemProvider = new ModItemProvider(this);
		}

		return modItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Div} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DivItemProvider divItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Div}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDivAdapter() {
		if (divItemProvider == null) {
			divItemProvider = new DivItemProvider(this);
		}

		return divItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Neg} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegItemProvider negItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Neg}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegAdapter() {
		if (negItemProvider == null) {
			negItemProvider = new NegItemProvider(this);
		}

		return negItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Not} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotItemProvider notItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Not}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNotAdapter() {
		if (notItemProvider == null) {
			notItemProvider = new NotItemProvider(this);
		}

		return notItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Cast} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CastItemProvider castItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Cast}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCastAdapter() {
		if (castItemProvider == null) {
			castItemProvider = new CastItemProvider(this);
		}

		return castItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.CreateObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateObjectItemProvider createObjectItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.CreateObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateObjectAdapter() {
		if (createObjectItemProvider == null) {
			createObjectItemProvider = new CreateObjectItemProvider(this);
		}

		return createObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.NullLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NullLiteralItemProvider nullLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.NullLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNullLiteralAdapter() {
		if (nullLiteralItemProvider == null) {
			nullLiteralItemProvider = new NullLiteralItemProvider(this);
		}

		return nullLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.TimeLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimeLiteralItemProvider timeLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.TimeLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimeLiteralAdapter() {
		if (timeLiteralItemProvider == null) {
			timeLiteralItemProvider = new TimeLiteralItemProvider(this);
		}

		return timeLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ActiveLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActiveLiteralItemProvider activeLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ActiveLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActiveLiteralAdapter() {
		if (activeLiteralItemProvider == null) {
			activeLiteralItemProvider = new ActiveLiteralItemProvider(this);
		}

		return activeLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.StringLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringLiteralItemProvider stringLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.StringLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringLiteralAdapter() {
		if (stringLiteralItemProvider == null) {
			stringLiteralItemProvider = new StringLiteralItemProvider(this);
		}

		return stringLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.IntLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntLiteralItemProvider intLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.IntLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntLiteralAdapter() {
		if (intLiteralItemProvider == null) {
			intLiteralItemProvider = new IntLiteralItemProvider(this);
		}

		return intLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.TrueLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrueLiteralItemProvider trueLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.TrueLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrueLiteralAdapter() {
		if (trueLiteralItemProvider == null) {
			trueLiteralItemProvider = new TrueLiteralItemProvider(this);
		}

		return trueLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.FalseLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FalseLiteralItemProvider falseLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.FalseLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFalseLiteralAdapter() {
		if (falseLiteralItemProvider == null) {
			falseLiteralItemProvider = new FalseLiteralItemProvider(this);
		}

		return falseLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.DoubleLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DoubleLiteralItemProvider doubleLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.DoubleLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDoubleLiteralAdapter() {
		if (doubleLiteralItemProvider == null) {
			doubleLiteralItemProvider = new DoubleLiteralItemProvider(this);
		}

		return doubleLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.UniqueIdExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UniqueIdExprItemProvider uniqueIdExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.UniqueIdExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUniqueIdExprAdapter() {
		if (uniqueIdExprItemProvider == null) {
			uniqueIdExprItemProvider = new UniqueIdExprItemProvider(this);
		}

		return uniqueIdExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ExpandExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpandExprItemProvider expandExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ExpandExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpandExprAdapter() {
		if (expandExprItemProvider == null) {
			expandExprItemProvider = new ExpandExprItemProvider(this);
		}

		return expandExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ParseExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParseExprItemProvider parseExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ParseExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParseExprAdapter() {
		if (parseExprItemProvider == null) {
			parseExprItemProvider = new ParseExprItemProvider(this);
		}

		return parseExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.PredefinedId} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PredefinedIdItemProvider predefinedIdItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.PredefinedId}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPredefinedIdAdapter() {
		if (predefinedIdItemProvider == null) {
			predefinedIdItemProvider = new PredefinedIdItemProvider(this);
		}

		return predefinedIdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.MeLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeLiteralItemProvider meLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.MeLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeLiteralAdapter() {
		if (meLiteralItemProvider == null) {
			meLiteralItemProvider = new MeLiteralItemProvider(this);
		}

		return meLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.SuperLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SuperLiteralItemProvider superLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.SuperLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSuperLiteralAdapter() {
		if (superLiteralItemProvider == null) {
			superLiteralItemProvider = new SuperLiteralItemProvider(this);
		}

		return superLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.MetaLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetaLiteralItemProvider metaLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.MetaLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetaLiteralAdapter() {
		if (metaLiteralItemProvider == null) {
			metaLiteralItemProvider = new MetaLiteralItemProvider(this);
		}

		return metaLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.TypeLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeLiteralItemProvider typeLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.TypeLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeLiteralAdapter() {
		if (typeLiteralItemProvider == null) {
			typeLiteralItemProvider = new TypeLiteralItemProvider(this);
		}

		return typeLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.SizeOfArray} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SizeOfArrayItemProvider sizeOfArrayItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.SizeOfArray}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSizeOfArrayAdapter() {
		if (sizeOfArrayItemProvider == null) {
			sizeOfArrayItemProvider = new SizeOfArrayItemProvider(this);
		}

		return sizeOfArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.IdExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IdExprItemProvider idExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.IdExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIdExprAdapter() {
		if (idExprItemProvider == null) {
			idExprItemProvider = new IdExprItemProvider(this);
		}

		return idExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.CallPart} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallPartItemProvider callPartItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.CallPart}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallPartAdapter() {
		if (callPartItemProvider == null) {
			callPartItemProvider = new CallPartItemProvider(this);
		}

		return callPartItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.VariableAccess} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableAccessItemProvider variableAccessItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.VariableAccess}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableAccessAdapter() {
		if (variableAccessItemProvider == null) {
			variableAccessItemProvider = new VariableAccessItemProvider(this);
		}

		return variableAccessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.MetaAccess} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetaAccessItemProvider metaAccessItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.MetaAccess}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetaAccessAdapter() {
		if (metaAccessItemProvider == null) {
			metaAccessItemProvider = new MetaAccessItemProvider(this);
		}

		return metaAccessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.TypeAccess} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeAccessItemProvider typeAccessItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.TypeAccess}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeAccessAdapter() {
		if (typeAccessItemProvider == null) {
			typeAccessItemProvider = new TypeAccessItemProvider(this);
		}

		return typeAccessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ExtensionDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtensionDefinitionItemProvider extensionDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ExtensionDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtensionDefinitionAdapter() {
		if (extensionDefinitionItemProvider == null) {
			extensionDefinitionItemProvider = new ExtensionDefinitionItemProvider(this);
		}

		return extensionDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ExtensionSemanticsDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtensionSemanticsDefinitionItemProvider extensionSemanticsDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ExtensionSemanticsDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtensionSemanticsDefinitionAdapter() {
		if (extensionSemanticsDefinitionItemProvider == null) {
			extensionSemanticsDefinitionItemProvider = new ExtensionSemanticsDefinitionItemProvider(this);
		}

		return extensionSemanticsDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.TextualSyntaxDef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextualSyntaxDefItemProvider textualSyntaxDefItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.TextualSyntaxDef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextualSyntaxDefAdapter() {
		if (textualSyntaxDefItemProvider == null) {
			textualSyntaxDefItemProvider = new TextualSyntaxDefItemProvider(this);
		}

		return textualSyntaxDefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.TsRule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TsRuleItemProvider tsRuleItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.TsRule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTsRuleAdapter() {
		if (tsRuleItemProvider == null) {
			tsRuleItemProvider = new TsRuleItemProvider(this);
		}

		return tsRuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.RhsExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RhsExpressionItemProvider rhsExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.RhsExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRhsExpressionAdapter() {
		if (rhsExpressionItemProvider == null) {
			rhsExpressionItemProvider = new RhsExpressionItemProvider(this);
		}

		return rhsExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L3RhsExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L3RhsExprItemProvider l3RhsExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L3RhsExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL3RhsExprAdapter() {
		if (l3RhsExprItemProvider == null) {
			l3RhsExprItemProvider = new L3RhsExprItemProvider(this);
		}

		return l3RhsExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L2RhsExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L2RhsExprItemProvider l2RhsExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L2RhsExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL2RhsExprAdapter() {
		if (l2RhsExprItemProvider == null) {
			l2RhsExprItemProvider = new L2RhsExprItemProvider(this);
		}

		return l2RhsExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.SequenceExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SequenceExprItemProvider sequenceExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.SequenceExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSequenceExprAdapter() {
		if (sequenceExprItemProvider == null) {
			sequenceExprItemProvider = new SequenceExprItemProvider(this);
		}

		return sequenceExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.L1RhsExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected L1RhsExprItemProvider l1RhsExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.L1RhsExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createL1RhsExprAdapter() {
		if (l1RhsExprItemProvider == null) {
			l1RhsExprItemProvider = new L1RhsExprItemProvider(this);
		}

		return l1RhsExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.TerminalExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TerminalExprItemProvider terminalExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.TerminalExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTerminalExprAdapter() {
		if (terminalExprItemProvider == null) {
			terminalExprItemProvider = new TerminalExprItemProvider(this);
		}

		return terminalExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.PropertyBindingExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyBindingExprItemProvider propertyBindingExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.PropertyBindingExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyBindingExprAdapter() {
		if (propertyBindingExprItemProvider == null) {
			propertyBindingExprItemProvider = new PropertyBindingExprItemProvider(this);
		}

		return propertyBindingExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.RhsClassifierExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RhsClassifierExprItemProvider rhsClassifierExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.RhsClassifierExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRhsClassifierExprAdapter() {
		if (rhsClassifierExprItemProvider == null) {
			rhsClassifierExprItemProvider = new RhsClassifierExprItemProvider(this);
		}

		return rhsClassifierExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.IdPropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IdPropertyTypeItemProvider idPropertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.IdPropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIdPropertyTypeAdapter() {
		if (idPropertyTypeItemProvider == null) {
			idPropertyTypeItemProvider = new IdPropertyTypeItemProvider(this);
		}

		return idPropertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.IntPropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntPropertyTypeItemProvider intPropertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.IntPropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntPropertyTypeAdapter() {
		if (intPropertyTypeItemProvider == null) {
			intPropertyTypeItemProvider = new IntPropertyTypeItemProvider(this);
		}

		return intPropertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.StringPropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringPropertyTypeItemProvider stringPropertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.StringPropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringPropertyTypeAdapter() {
		if (stringPropertyTypeItemProvider == null) {
			stringPropertyTypeItemProvider = new StringPropertyTypeItemProvider(this);
		}

		return stringPropertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.BooleanPropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanPropertyTypeItemProvider booleanPropertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.BooleanPropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanPropertyTypeAdapter() {
		if (booleanPropertyTypeItemProvider == null) {
			booleanPropertyTypeItemProvider = new BooleanPropertyTypeItemProvider(this);
		}

		return booleanPropertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.StructuredPropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StructuredPropertyTypeItemProvider structuredPropertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.StructuredPropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStructuredPropertyTypeAdapter() {
		if (structuredPropertyTypeItemProvider == null) {
			structuredPropertyTypeItemProvider = new StructuredPropertyTypeItemProvider(this);
		}

		return structuredPropertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.CompositePropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositePropertyTypeItemProvider compositePropertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.CompositePropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositePropertyTypeAdapter() {
		if (compositePropertyTypeItemProvider == null) {
			compositePropertyTypeItemProvider = new CompositePropertyTypeItemProvider(this);
		}

		return compositePropertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ReferencePropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferencePropertyTypeItemProvider referencePropertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ReferencePropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferencePropertyTypeAdapter() {
		if (referencePropertyTypeItemProvider == null) {
			referencePropertyTypeItemProvider = new ReferencePropertyTypeItemProvider(this);
		}

		return referencePropertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.MetaExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetaExprItemProvider metaExprItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.MetaExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetaExprAdapter() {
		if (metaExprItemProvider == null) {
			metaExprItemProvider = new MetaExprItemProvider(this);
		}

		return metaExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.TargetStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TargetStatementItemProvider targetStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.TargetStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTargetStatementAdapter() {
		if (targetStatementItemProvider == null) {
			targetStatementItemProvider = new TargetStatementItemProvider(this);
		}

		return targetStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ExpansionStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpansionStatementItemProvider expansionStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ExpansionStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpansionStatementAdapter() {
		if (expansionStatementItemProvider == null) {
			expansionStatementItemProvider = new ExpansionStatementItemProvider(this);
		}

		return expansionStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ExpandTextPart} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpandTextPartItemProvider expandTextPartItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ExpandTextPart}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpandTextPartAdapter() {
		if (expandTextPartItemProvider == null) {
			expandTextPartItemProvider = new ExpandTextPartItemProvider(this);
		}

		return expandTextPartItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ExpandVariablePart} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpandVariablePartItemProvider expandVariablePartItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ExpandVariablePart}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpandVariablePartAdapter() {
		if (expandVariablePartItemProvider == null) {
			expandVariablePartItemProvider = new ExpandVariablePartItemProvider(this);
		}

		return expandVariablePartItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.SetExpansionContextStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetExpansionContextStatementItemProvider setExpansionContextStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.SetExpansionContextStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetExpansionContextStatementAdapter() {
		if (setExpansionContextStatementItemProvider == null) {
			setExpansionContextStatementItemProvider = new SetExpansionContextStatementItemProvider(this);
		}

		return setExpansionContextStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.SaveGenStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SaveGenStatementItemProvider saveGenStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.SaveGenStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSaveGenStatementAdapter() {
		if (saveGenStatementItemProvider == null) {
			saveGenStatementItemProvider = new SaveGenStatementItemProvider(this);
		}

		return saveGenStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ResumeGenStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResumeGenStatementItemProvider resumeGenStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ResumeGenStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResumeGenStatementAdapter() {
		if (resumeGenStatementItemProvider == null) {
			resumeGenStatementItemProvider = new ResumeGenStatementItemProvider(this);
		}

		return resumeGenStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ExpandExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpandExpressionItemProvider expandExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ExpandExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpandExpressionAdapter() {
		if (expandExpressionItemProvider == null) {
			expandExpressionItemProvider = new ExpandExpressionItemProvider(this);
		}

		return expandExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.ExpandStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpandStatementItemProvider expandStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.ExpandStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpandStatementAdapter() {
		if (expandStatementItemProvider == null) {
			expandStatementItemProvider = new ExpandStatementItemProvider(this);
		}

		return expandStatementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.CodeQuoteExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodeQuoteExpressionItemProvider codeQuoteExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.CodeQuoteExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodeQuoteExpressionAdapter() {
		if (codeQuoteExpressionItemProvider == null) {
			codeQuoteExpressionItemProvider = new CodeQuoteExpressionItemProvider(this);
		}

		return codeQuoteExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.QuotedCode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuotedCodeItemProvider quotedCodeItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.QuotedCode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuotedCodeAdapter() {
		if (quotedCodeItemProvider == null) {
			quotedCodeItemProvider = new QuotedCodeItemProvider(this);
		}

		return quotedCodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.QuotedExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuotedExpressionItemProvider quotedExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.QuotedExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuotedExpressionAdapter() {
		if (quotedExpressionItemProvider == null) {
			quotedExpressionItemProvider = new QuotedExpressionItemProvider(this);
		}

		return quotedExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.QuotedStatements} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuotedStatementsItemProvider quotedStatementsItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.QuotedStatements}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuotedStatementsAdapter() {
		if (quotedStatementsItemProvider == null) {
			quotedStatementsItemProvider = new QuotedStatementsItemProvider(this);
		}

		return quotedStatementsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.QuotedClassContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuotedClassContentItemProvider quotedClassContentItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.QuotedClassContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuotedClassContentAdapter() {
		if (quotedClassContentItemProvider == null) {
			quotedClassContentItemProvider = new QuotedClassContentItemProvider(this);
		}

		return quotedClassContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.QuotedModuleContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuotedModuleContentItemProvider quotedModuleContentItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.QuotedModuleContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuotedModuleContentAdapter() {
		if (quotedModuleContentItemProvider == null) {
			quotedModuleContentItemProvider = new QuotedModuleContentItemProvider(this);
		}

		return quotedModuleContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.Pattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PatternItemProvider patternItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.Pattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPatternAdapter() {
		if (patternItemProvider == null) {
			patternItemProvider = new PatternItemProvider(this);
		}

		return patternItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hub.sam.dbl.TestStatement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TestStatementItemProvider testStatementItemProvider;

	/**
	 * This creates an adapter for a {@link hub.sam.dbl.TestStatement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTestStatementAdapter() {
		if (testStatementItemProvider == null) {
			testStatementItemProvider = new TestStatementItemProvider(this);
		}

		return testStatementItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (constructItemProvider != null) constructItemProvider.dispose();
		if (extensibleElementItemProvider != null) extensibleElementItemProvider.dispose();
		if (modelItemProvider != null) modelItemProvider.dispose();
		if (importItemProvider != null) importItemProvider.dispose();
		if (moduleItemProvider != null) moduleItemProvider.dispose();
		if (constructiveExtensionItemProvider != null) constructiveExtensionItemProvider.dispose();
		if (moduleContentItemProvider != null) moduleContentItemProvider.dispose();
		if (classContentItemProvider != null) classContentItemProvider.dispose();
		if (arrayDimensionItemProvider != null) arrayDimensionItemProvider.dispose();
		if (voidTypeItemProvider != null) voidTypeItemProvider.dispose();
		if (intTypeItemProvider != null) intTypeItemProvider.dispose();
		if (boolTypeItemProvider != null) boolTypeItemProvider.dispose();
		if (doubleTypeItemProvider != null) doubleTypeItemProvider.dispose();
		if (stringTypeItemProvider != null) stringTypeItemProvider.dispose();
		if (functionItemProvider != null) functionItemProvider.dispose();
		if (nativeBindingItemProvider != null) nativeBindingItemProvider.dispose();
		if (superClassSpecificationItemProvider != null) superClassSpecificationItemProvider.dispose();
		if (classItemProvider != null) classItemProvider.dispose();
		if (constructorItemProvider != null) constructorItemProvider.dispose();
		if (variableItemProvider != null) variableItemProvider.dispose();
		if (parameterItemProvider != null) parameterItemProvider.dispose();
		if (namedElementItemProvider != null) namedElementItemProvider.dispose();
		if (statementItemProvider != null) statementItemProvider.dispose();
		if (loopStatementItemProvider != null) loopStatementItemProvider.dispose();
		if (simpleStatementItemProvider != null) simpleStatementItemProvider.dispose();
		if (assignmentItemProvider != null) assignmentItemProvider.dispose();
		if (functionCallItemProvider != null) functionCallItemProvider.dispose();
		if (returnItemProvider != null) returnItemProvider.dispose();
		if (waitUntilItemProvider != null) waitUntilItemProvider.dispose();
		if (terminateItemProvider != null) terminateItemProvider.dispose();
		if (yieldItemProvider != null) yieldItemProvider.dispose();
		if (waitItemProvider != null) waitItemProvider.dispose();
		if (reactivateItemProvider != null) reactivateItemProvider.dispose();
		if (activateObjectItemProvider != null) activateObjectItemProvider.dispose();
		if (advanceItemProvider != null) advanceItemProvider.dispose();
		if (printItemProvider != null) printItemProvider.dispose();
		if (ifStatementItemProvider != null) ifStatementItemProvider.dispose();
		if (localScopeItemProvider != null) localScopeItemProvider.dispose();
		if (localScopeStatementItemProvider != null) localScopeStatementItemProvider.dispose();
		if (forStatementItemProvider != null) forStatementItemProvider.dispose();
		if (whileStatementItemProvider != null) whileStatementItemProvider.dispose();
		if (switchStatementItemProvider != null) switchStatementItemProvider.dispose();
		if (switchCaseItemProvider != null) switchCaseItemProvider.dispose();
		if (breakStatementItemProvider != null) breakStatementItemProvider.dispose();
		if (continueStatementItemProvider != null) continueStatementItemProvider.dispose();
		if (expressionItemProvider != null) expressionItemProvider.dispose();
		if (l1ExprItemProvider != null) l1ExprItemProvider.dispose();
		if (l2ExprItemProvider != null) l2ExprItemProvider.dispose();
		if (l3ExprItemProvider != null) l3ExprItemProvider.dispose();
		if (l4ExprItemProvider != null) l4ExprItemProvider.dispose();
		if (l5ExprItemProvider != null) l5ExprItemProvider.dispose();
		if (l6ExprItemProvider != null) l6ExprItemProvider.dispose();
		if (l7ExprItemProvider != null) l7ExprItemProvider.dispose();
		if (l8ExprItemProvider != null) l8ExprItemProvider.dispose();
		if (l9ExprItemProvider != null) l9ExprItemProvider.dispose();
		if (orItemProvider != null) orItemProvider.dispose();
		if (andItemProvider != null) andItemProvider.dispose();
		if (notEqualItemProvider != null) notEqualItemProvider.dispose();
		if (equalItemProvider != null) equalItemProvider.dispose();
		if (greaterItemProvider != null) greaterItemProvider.dispose();
		if (greaterEqualItemProvider != null) greaterEqualItemProvider.dispose();
		if (lessItemProvider != null) lessItemProvider.dispose();
		if (lessEqualItemProvider != null) lessEqualItemProvider.dispose();
		if (instanceOfItemProvider != null) instanceOfItemProvider.dispose();
		if (plusItemProvider != null) plusItemProvider.dispose();
		if (minusItemProvider != null) minusItemProvider.dispose();
		if (mulItemProvider != null) mulItemProvider.dispose();
		if (modItemProvider != null) modItemProvider.dispose();
		if (divItemProvider != null) divItemProvider.dispose();
		if (negItemProvider != null) negItemProvider.dispose();
		if (notItemProvider != null) notItemProvider.dispose();
		if (castItemProvider != null) castItemProvider.dispose();
		if (createObjectItemProvider != null) createObjectItemProvider.dispose();
		if (nullLiteralItemProvider != null) nullLiteralItemProvider.dispose();
		if (timeLiteralItemProvider != null) timeLiteralItemProvider.dispose();
		if (activeLiteralItemProvider != null) activeLiteralItemProvider.dispose();
		if (stringLiteralItemProvider != null) stringLiteralItemProvider.dispose();
		if (intLiteralItemProvider != null) intLiteralItemProvider.dispose();
		if (trueLiteralItemProvider != null) trueLiteralItemProvider.dispose();
		if (falseLiteralItemProvider != null) falseLiteralItemProvider.dispose();
		if (doubleLiteralItemProvider != null) doubleLiteralItemProvider.dispose();
		if (uniqueIdExprItemProvider != null) uniqueIdExprItemProvider.dispose();
		if (expandExprItemProvider != null) expandExprItemProvider.dispose();
		if (parseExprItemProvider != null) parseExprItemProvider.dispose();
		if (predefinedIdItemProvider != null) predefinedIdItemProvider.dispose();
		if (meLiteralItemProvider != null) meLiteralItemProvider.dispose();
		if (superLiteralItemProvider != null) superLiteralItemProvider.dispose();
		if (metaLiteralItemProvider != null) metaLiteralItemProvider.dispose();
		if (typeLiteralItemProvider != null) typeLiteralItemProvider.dispose();
		if (sizeOfArrayItemProvider != null) sizeOfArrayItemProvider.dispose();
		if (idExprItemProvider != null) idExprItemProvider.dispose();
		if (callPartItemProvider != null) callPartItemProvider.dispose();
		if (variableAccessItemProvider != null) variableAccessItemProvider.dispose();
		if (metaAccessItemProvider != null) metaAccessItemProvider.dispose();
		if (typeAccessItemProvider != null) typeAccessItemProvider.dispose();
		if (extensionDefinitionItemProvider != null) extensionDefinitionItemProvider.dispose();
		if (extensionSemanticsDefinitionItemProvider != null) extensionSemanticsDefinitionItemProvider.dispose();
		if (textualSyntaxDefItemProvider != null) textualSyntaxDefItemProvider.dispose();
		if (tsRuleItemProvider != null) tsRuleItemProvider.dispose();
		if (rhsExpressionItemProvider != null) rhsExpressionItemProvider.dispose();
		if (l3RhsExprItemProvider != null) l3RhsExprItemProvider.dispose();
		if (l2RhsExprItemProvider != null) l2RhsExprItemProvider.dispose();
		if (sequenceExprItemProvider != null) sequenceExprItemProvider.dispose();
		if (l1RhsExprItemProvider != null) l1RhsExprItemProvider.dispose();
		if (terminalExprItemProvider != null) terminalExprItemProvider.dispose();
		if (propertyBindingExprItemProvider != null) propertyBindingExprItemProvider.dispose();
		if (rhsClassifierExprItemProvider != null) rhsClassifierExprItemProvider.dispose();
		if (idPropertyTypeItemProvider != null) idPropertyTypeItemProvider.dispose();
		if (intPropertyTypeItemProvider != null) intPropertyTypeItemProvider.dispose();
		if (stringPropertyTypeItemProvider != null) stringPropertyTypeItemProvider.dispose();
		if (booleanPropertyTypeItemProvider != null) booleanPropertyTypeItemProvider.dispose();
		if (structuredPropertyTypeItemProvider != null) structuredPropertyTypeItemProvider.dispose();
		if (compositePropertyTypeItemProvider != null) compositePropertyTypeItemProvider.dispose();
		if (referencePropertyTypeItemProvider != null) referencePropertyTypeItemProvider.dispose();
		if (metaExprItemProvider != null) metaExprItemProvider.dispose();
		if (targetStatementItemProvider != null) targetStatementItemProvider.dispose();
		if (expansionStatementItemProvider != null) expansionStatementItemProvider.dispose();
		if (expandTextPartItemProvider != null) expandTextPartItemProvider.dispose();
		if (expandVariablePartItemProvider != null) expandVariablePartItemProvider.dispose();
		if (setExpansionContextStatementItemProvider != null) setExpansionContextStatementItemProvider.dispose();
		if (saveGenStatementItemProvider != null) saveGenStatementItemProvider.dispose();
		if (resumeGenStatementItemProvider != null) resumeGenStatementItemProvider.dispose();
		if (expandExpressionItemProvider != null) expandExpressionItemProvider.dispose();
		if (expandStatementItemProvider != null) expandStatementItemProvider.dispose();
		if (codeQuoteExpressionItemProvider != null) codeQuoteExpressionItemProvider.dispose();
		if (quotedCodeItemProvider != null) quotedCodeItemProvider.dispose();
		if (quotedExpressionItemProvider != null) quotedExpressionItemProvider.dispose();
		if (quotedStatementsItemProvider != null) quotedStatementsItemProvider.dispose();
		if (quotedClassContentItemProvider != null) quotedClassContentItemProvider.dispose();
		if (quotedModuleContentItemProvider != null) quotedModuleContentItemProvider.dispose();
		if (patternItemProvider != null) patternItemProvider.dispose();
		if (testStatementItemProvider != null) testStatementItemProvider.dispose();
	}

}
